### ISSUE TITLE
license

### ISSUE THREAD

**Issue by justinmk** [lewis6991/fileline.nvim#2]
Needs a license file, hopefully Apache 2.0 :)

**Comment by lewis6991** [comment]
Woops, thought I added one. I usually go MIT, how does Apache 2.0 differ?

**Comment by justinmk** [comment]
MIT is fine too. Apache has some extra stuff for patents and matches Nvim's license.

**Comment by lewis6991** [comment]
https://github.com/lewis6991/fileline.nvim/commit/87cc2e35199b43124d52dc3114614dd60d968d05
